#手动创建一个pv和pvc测试一下nfs是否可用
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/nfs/volumes
    server: 172.17.64.138

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-test-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
