apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      k8s-app: etcd
    name: etcd
    namespace: kube-system
  spec:
    ports:
    - name: port
      port: 2379
      protocol: TCP
      targetPort: 2379
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Endpoints
  metadata:
    labels:
      k8s-app: etcd
    name: etcd
    namespace: kube-system
  subsets:
  - addresses:
    - ip: 172.17.64.138
    ports:
    - name: port
      port: 2379
      protocol: TCP
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
