apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      k8s-app: kube-scheduler
    name: kube-scheduler-monitor
    namespace: kube-system
  spec:
    ports:
    - name: http-metrics
      port: 10251
      protocol: TCP
      targetPort: 10251
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Endpoints
  metadata:
    labels:
      k8s-app: kube-scheduler
    name: kube-scheduler-monitor
    namespace: kube-system
  subsets:
  - addresses:
    - ip: 172.17.64.138
    ports:
    - name: http-metrics
      port: 10251
      protocol: TCP
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
